apiVersion networking.k8s.iov1
kind Ingress
metadata
  name heart-disease-ingress
  annotations
    nginx.ingress.kubernetes.iorewrite-target 
spec
  rules
    - host heart.local
      http
        paths
          - path 
            pathType Prefix
            backend
              service
                name heart-disease-service
                port
                  number 80
